# -*- coding: utf-8 -*-

"""
/***************************************************************************
 pctools
                                 A QGIS plugin
 PointCloud Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-01-03
        copyright            : (C) 2018 by Paul Blottiere
        email                : blottiere.paul@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Paul Blottiere'
__date__ = '2018-01-03'
__copyright__ = '(C) 2018 by Paul Blottiere'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingProvider
from .pgpointcloud_import import PgPointCloudImport
from .extent_import import ExtentImport


class Provider(QgsProcessingProvider):

    def __init__(self):
        QgsProcessingProvider.__init__(self)

        # Load algorithms
        self.alglist = [PgPointCloudImport(), ExtentImport()]

    def unload(self):
        pass

    def loadAlgorithms(self):
        for alg in self.alglist:
            self.addAlgorithm( alg )

    def id(self):
        return 'PCTools'

    def name(self):
        return self.tr('PCTools')

    def longName(self):
        return self.name()
